In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [40]:
data = np.array([18,22,25,27,42,43])
n = len(data)
clusters = [[data[i]] for i in range(n)]
matrix = np.zeros((n,n))
print(data,n,matrix,clusters)

[18 22 25 27 42 43] 6 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] [[18], [22], [25], [27], [42], [43]]


In [41]:
for i in range(n):
    for j in range(n):
        matrix[i][j] = np.abs(data[i] - data[j])
print(matrix)

[[ 0.  4.  7.  9. 24. 25.]
 [ 4.  0.  3.  5. 20. 21.]
 [ 7.  3.  0.  2. 17. 18.]
 [ 9.  5.  2.  0. 15. 16.]
 [24. 20. 17. 15.  0.  1.]
 [25. 21. 18. 16.  1.  0.]]


In [42]:

# Extract the lower triangular part, including the diagonal
lower_triangular = np.tril(matrix)
# Find the minimum non-zero element
non_zero_min = np.min(lower_triangular[lower_triangular > 0])
# Get the indices of the minimum non-zero element
i, j = np.where(lower_triangular == non_zero_min)
# Ensure i and j are integer scalars by converting the first elements of i and j
i, j = int(i[0]), int(j[0])

print("Smallest non-zero element:", non_zero_min)
print("Indices (i, j):", (i, j))
print(lower_triangular)

Smallest non-zero element: 1.0
Indices (i, j): (5, 4)
[[ 0.  0.  0.  0.  0.  0.]
 [ 4.  0.  0.  0.  0.  0.]
 [ 7.  3.  0.  0.  0.  0.]
 [ 9.  5.  2.  0.  0.  0.]
 [24. 20. 17. 15.  0.  0.]
 [25. 21. 18. 16.  1.  0.]]


In [43]:
# Merge clusters[i] into clusters[j]
clusters[j] += clusters[i]

# Delete the merged cluster
del clusters[i]

print("Updated clusters:", clusters)

Updated clusters: [[18], [22], [25], [27], [42, 43]]


In [44]:
m = len(clusters)
matrix = np.zeros((m,m))
for i in range(m):
    for j in range(m):
        matrix[i][j] = np.min([np.abs(p1 - p2) for p1 in clusters[i] for p2 in clusters[j]])
print(matrix)

[[ 0.  4.  7.  9. 24.]
 [ 4.  0.  3.  5. 20.]
 [ 7.  3.  0.  2. 17.]
 [ 9.  5.  2.  0. 15.]
 [24. 20. 17. 15.  0.]]


In [45]:
# Extract the lower triangular part, including the diagonal
lower_triangular = np.tril(matrix)
# Find the minimum non-zero element
non_zero_min = np.min(lower_triangular[lower_triangular > 0])
# Get the indices of the minimum non-zero element
i, j = np.where(lower_triangular == non_zero_min)
i, j = int(i[0]), int(j[0])

print("Smallest non-zero element:", non_zero_min)
print("Indices (i, j):", (i, j))
print(lower_triangular)

Smallest non-zero element: 2.0
Indices (i, j): (3, 2)
[[ 0.  0.  0.  0.  0.]
 [ 4.  0.  0.  0.  0.]
 [ 7.  3.  0.  0.  0.]
 [ 9.  5.  2.  0.  0.]
 [24. 20. 17. 15.  0.]]


In [46]:
# Merge clusters[i] into clusters[j]
clusters[j] += clusters[i]

# Delete the merged cluster
del clusters[i]

print("Updated clusters:", clusters)

Updated clusters: [[18], [22], [25, 27], [42, 43]]


In [47]:
m = len(clusters)
matrix = np.zeros((m,m))
for i in range(m):
    for j in range(m):
        matrix[i][j] = np.min([np.abs(p1 - p2) for p1 in clusters[i] for p2 in clusters[j]])
print(matrix)

[[ 0.  4.  7. 24.]
 [ 4.  0.  3. 20.]
 [ 7.  3.  0. 15.]
 [24. 20. 15.  0.]]


In [48]:
data = np.array([(1, 1), (3, 2), (9, 1), (3, 7), (7, 2), 
                   (9, 7), (4, 8), (8, 3), (1, 4)])

In [49]:
n = len(data)
clusters = [[data[i]] for i in range(n)]

In [50]:
print(clusters)

[[array([1, 1])], [array([3, 2])], [array([9, 1])], [array([3, 7])], [array([7, 2])], [array([9, 7])], [array([4, 8])], [array([8, 3])], [array([1, 4])]]
