### Question 1

In [1]:
import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8])
a = a.reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Question 2

In [2]:
a=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a = np.where(a%2==1,-1,a)
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Question 3

In [3]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

print(np.where(x>y)[0])
print(np.where(x==y)[0])

[1 2 4 5 6 7 8 9]
[0]


### Question 4

In [4]:
a = np.arange(100).reshape(5,-1)
print(a[:,:4])

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]


### Additional Question 1

In [5]:
a = np.random.randint(30, 41, size=10)
print(a)

[31 33 32 39 38 40 39 40 30 39]


### Addtional Question 2

In [6]:
A=np.array([[1,2,3],[4,5,6],[7,8,10]])
B=np.array([[7,8,10],[4,5,6],[1,2,3]])

#### Addition and Subtraction

In [7]:
C = A+B
E = A-B
print(C)
print(E)

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]


#### Sum of all elements of A, columns of B and rows of C

In [8]:
print(np.sum(A))
print(np.sum(B,axis = 0))
print(np.sum(C,axis = 1))

46
[12 15 19]
[31 30 31]


#### Product of A and B

In [9]:
D = np.dot(A,B)
print(D)

[[ 18  24  31]
 [ 54  69  88]
 [ 91 116 148]]


#### Sort C

In [10]:
E = np.sort(C)
print(E)

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]


#### Transpose of E

In [11]:
print(E.T)

[[ 8  8  8]
 [10 10 10]
 [13 12 13]]
